[package]
name = "openimc"
version = "0.1.0"
edition = "2021"


[lib]
name = "openimc"
crate-type = ["cdylib"]


[dependencies]
once_cell = "1.17"
pyo3 = "0.18"
cxx = "1.0"
ethercat = "0.2.4"
byteorder = "1.4"
thread-priority = "0.10"


[build-dependencies]
cxx-build = "1.0"
